server:
  ip: http://localhost:8000
  key: demo
worker:
  blender_bin: C:\Program Files (x86)\Steam\steamapps\common\Blender\blender.exe
  name: DESKTOP-RMSABPR
  working_dir: C:\Users\benhu\Desktop\remote_test\
