server:
  ip: http://127.0.0.1:8000
  key: demo
worker:
  blender_bin: D:\Games\Steam\steamapps\common\Blender\blender.exe
  name: DESKTOP-RMSABPR
  working_dir: D:\OneDrive - Groupe E.D.H\PFE\Rendu\Scenes
