server:
  ip: http://109.0.239.156:8000
  key: demo
worker:
  blender_bin: C:\Program Files (x86)\Steam\steamapps\common\Blenderblender.exe
  name: LYOB22W262
  working_dir: D:\OneDrive - Groupe E.D.H\PFE\Rendu\Scenes
